SELECT P.NOME_COMPLETO, SUM(PC.SALARIO) AS SALARIO_TOTAL,
    SUM(C.SALARIO_PADRAO) AS SALARIO_PADRAO_TOTAL

FROM PESSOA_CARGOS PC
    INNER JOIN PESSOA P ON (PC.CPF = P.CPF)
    INNER JOIN CARGOS C ON (PC.ID_CARGO = C.ID)

WHERE PC.SALARIO IS NOT NULL

GROUP BY P.NOME_COMPLETO
ORDER BY P.NOME_COMPLETO;